"""Module containing classes for file based synchronization between processes."""

import fcntl
from io import TextIOWrapper
from pathlib import Path
from typing import Any, Self


class LockFile:
    """
    Context manager implementing file based locking.

    (TODO: Consider using https://github.com/WoLpH/portalocker or https://linux.die.net/man/3/sem_open instead)
    """

    @staticmethod
    def get_base_path() -> Path:
        """Path of directory containing lock files generated by instances of this class.

        Returns
        -------
        Path
            The path of the base directory for lock files
        """
        return Path("/tmp")

    def __init__(self: Self, name: str) -> None:
        """
        Create a new instance to guard a critical section.

        Parameters
        ----------
        name : str
            The name of the lock corresponding to the lock file name
        """
        self.__path = LockFile.get_base_path() / name
        self.__path.parent.mkdir(parents=True, exist_ok=True)
        self.__path.touch()
        self.__file: TextIOWrapper[Any] | None = None

    def __enter__(self: Self) -> Self:
        if self.__file:
            raise RuntimeError("Re-entry not allowed")
        self.__file = open(self.__path)
        fcntl.flock(self.__file.fileno(), fcntl.LOCK_EX)
        return self

    def __exit__(self: Self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        if self.__file:
            fcntl.flock(self.__file.fileno(), fcntl.LOCK_UN)
            self.__file.close()
            self.__file = None
