[project]
name            = "meta-sched"
version         = "0.1.0"
description     = "Meta Scheduler"
authors         = [{name="Ruben Horn"}]
readme          = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fabric>=3.2.2",
    "flask>=3.1.0",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "typeguard>=4.4.2",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pyright>=1.1.393",
    # For static type checking
    "types-paramiko>=3.5.0",
    "types-requests>=2.32.0.20241016",
]

[project.scripts]
mscli     = "meta_sched:run_cli"
msservice = "meta_sched:run_service"

[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.uv]
package = true
environments = [
    "sys_platform == 'linux'",
]

[tool.mypy]
strict                 = true
ignore_missing_imports = true
exclude                = "meta_sched/data/examples"

[tool.pyright]
# For using pandas objects without excessive checking
reportOptionalMemberAccess = false
reportOptionalSubscript    = false
