host = "localhost"
port = 8001
db_url = "sqlite:///:memory:" # Use an ephemeral in-memory database

scheduler_class_name = "stochastic.py:WeightedByCores"
scheduling_loop_interval = 10


[[targets]]
# https://portal.hpc.hsu-hh.de/documentation/hsuper/partitions/
id = "hsuper-small"
host = "hsuper-login01.hsu-hh.de"
batch_system = "slurm"
queue = "small"
nodes = 571
cores_per_node = 72
max_time = "72:00:00"
max_nodes = 5
tags = ["x86"]
[targets.module_map]
MPI = "intel-oneapi-mpi"


[[targets]]
id = "windhpc-hsu-long"
host = "windhpc00.hsu-hh.de"
batch_system = "slurm"
queue = "long"
nodes = 3
cores_per_node = 48
max_time = "7-00:00:00"
source_scripts = ["/etc/profile"]
tags = ["x86"]
[targets.module_map]
MPI = "mpi"


[[targets]]
id = "windhpc-hlrs"
host = "training.hlrs.de"
batch_system = "pbs"
queue = "windhpc"
nodes = 5
cores_per_node = 48
max_time = "24:00:00"
tags = ["x86"]
[targets.module_map]
MPI = "mpi/openmpi"


[[targets]]
id = "windhpc-wwit"
host = "windpark.windhpc.de"
batch_system = "slurm"
nodes = 5
cores_per_node = 48
source_scripts = ["/etc/profile"]
tags = ["x86", "green"]
[targets.module_map]
MPI = "mpi/openmpi"
