"""Module containing general purpose utility classes and functions for the submit component."""

import fcntl
import os
import sys
from io import TextIOWrapper
from os import PathLike
from pathlib import Path
from typing import Any, Optional, Self


class SuppressStderr:
    """
    Context manager to suppresses all output to stderr.
    NOTE: This is NOT thread safe.
    """

    def __enter__(self: Self) -> Self:
        self._stderr = sys.stderr
        self._devnull = open(os.devnull, "w")
        sys.stderr = self._devnull
        return self

    def __exit__(self: Self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        sys.stderr = self._stderr
        self._devnull.close()


class RedirectOutputToFile:
    """Context manager for redirecting sys.stdout/sys.stderr (e.g. the output of all calls to print) to a file."""

    def __init__(
        self: Self,
        stdout: Optional[str | PathLike[Any]] = None,
        stderr: Optional[str | PathLike[Any]] = None,
    ) -> None:
        """
        Create a new instance to redirect stdout/stderr.

        Parameters
        ----------
        stdout : Optional[str | PathLike[Any]]
            Path to redirect sys.stdout to (default None does not redirect output)
        stderr : Optional[str | PathLike[Any]]
            Path to redirect sys.stderr to (default None does not redirect output)
        """
        self.__stdout_redirect = stdout
        self.__stderr_redirect = stderr
        self.__stdout = sys.stdout
        self.__stderr = sys.stderr

    def __enter__(self: Self) -> Self:
        if self.__stdout_redirect:
            sys.stdout = open(self.__stdout_redirect, "a")
        if self.__stderr_redirect:
            sys.stderr = open(self.__stderr_redirect, "a")
        return self

    def __exit__(self: Self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        if self.__stdout_redirect:
            sys.stdout.flush()
            sys.stdout.close()
            sys.stdout = self.__stdout
        if self.__stderr_redirect:
            sys.stderr.flush()
            sys.stderr.close()
            sys.stderr = self.__stderr


class LockFile:
    """
    Context manager implementing file based locking.

    (TODO: Consider using https://github.com/WoLpH/portalocker or https://linux.die.net/man/3/sem_open instead)
    """

    @staticmethod
    def get_base_path() -> Path:
        """Path of directory containing lock files generated by instances of this class.

        Returns
        -------
        Path
            The path of the base directory for lock files
        """
        return Path("/tmp")

    def __init__(self: Self, name: str) -> None:
        """
        Create a new instance to guard a critical section.

        Parameters
        ----------
        name : str
            The name of the lock corresponding to the lock file name
        """
        self.__path = LockFile.get_base_path() / name
        self.__path.parent.mkdir(parents=True, exist_ok=True)
        self.__path.touch()
        self.__file: Optional[TextIOWrapper[Any]] = None

    def __enter__(self: Self) -> Self:
        if self.__file:
            raise RuntimeError("Re-entry not allowed")
        self.__file = open(self.__path)
        fcntl.flock(self.__file.fileno(), fcntl.LOCK_EX)
        return self

    def __exit__(self: Self, exc_type: Any, exc_value: Any, traceback: Any) -> None:
        if self.__file:
            fcntl.flock(self.__file.fileno(), fcntl.LOCK_UN)
            self.__file.close()
            self.__file = None
