"""Module containing general purpose utility classes and functions for the submit component."""

import errno
import fcntl
import os
import sys
import time
from io import TextIOWrapper
from os import PathLike
from pathlib import Path
from typing import Any, Optional, TypeVar, Union

E = TypeVar("E", bound=BaseException)


def unwrap_error(
    error: BaseException, target_type: type[E], max_depth: int = 10
) -> Optional[E]:
    """
    Traverse the exception chain to find an exception of a specific type.

    Parameters
    ----------
    error : BaseException
        The error to be searched.
    target_type : Type[BaseException]
        The type of exception to look for.
    max_depth : int
        Maximum depth to traverse (default: 10).

    Returns
    -------
    Optional[BaseException]
        The first matching exception of the specified type, or None if not found.
    """
    seen: set[int] = set()
    for _ in range(max_depth):
        seen.add(id(error))
        if isinstance(error, target_type):
            return error
        # Traverse __cause__, __context__, or args
        next_error: Optional[BaseException] = getattr(
            error, "__cause__", None
        ) or getattr(error, "__context__", None)
        if not next_error and hasattr(error, "args"):
            for arg in error.args:
                if isinstance(arg, BaseException):
                    next_error = arg
                    break
        if not next_error or id(next_error) in seen:
            break
        error = next_error
    return None


class SuppressStderr:
    """
    Context manager to suppresses all output to stderr.
    NOTE: This is NOT thread safe.
    """

    def __enter__(self: "SuppressStderr") -> "SuppressStderr":
        self._stderr = sys.stderr
        self._devnull = open(os.devnull, "w")
        sys.stderr = self._devnull
        return self

    def __exit__(
        self: "SuppressStderr", exc_type: Any, exc_value: Any, traceback: Any
    ) -> None:
        sys.stderr = self._stderr
        self._devnull.close()


class RedirectOutputToFile:
    """Context manager for redirecting sys.stdout/sys.stderr (e.g. the output of all calls to print) to a file."""

    def __init__(
        self: "RedirectOutputToFile",
        stdout: Optional[Union[str, PathLike[Any]]] = None,
        stderr: Optional[Union[str, PathLike[Any]]] = None,
    ) -> None:
        """
        Create a new instance to redirect stdout/stderr.

        Parameters
        ----------
        stdout : Optional[Union[str, PathLike[Any]]]
            Path to redirect sys.stdout to (default None does not redirect output)
        stderr : Optional[Union[str, PathLike[Any]]]
            Path to redirect sys.stderr to (default None does not redirect output)
        """
        self.__stdout_redirect = stdout
        self.__stderr_redirect = stderr
        self.__stdout = sys.stdout
        self.__stderr = sys.stderr

    def __enter__(self: "RedirectOutputToFile") -> "RedirectOutputToFile":
        if self.__stdout_redirect:
            sys.stdout = open(self.__stdout_redirect, "a")
        if self.__stderr_redirect:
            sys.stderr = open(self.__stderr_redirect, "a")
        return self

    def __exit__(
        self: "RedirectOutputToFile", exc_type: Any, exc_value: Any, traceback: Any
    ) -> None:
        if self.__stdout_redirect:
            sys.stdout.flush()
            sys.stdout.close()
            sys.stdout = self.__stdout
        if self.__stderr_redirect:
            sys.stderr.flush()
            sys.stderr.close()
            sys.stderr = self.__stderr


class LockFile:
    """
    Context manager implementing file based locking.

    (TODO: Consider using https://github.com/WoLpH/portalocker or https://linux.die.net/man/3/sem_open instead)
    """

    @staticmethod
    def get_base_path() -> Path:
        """Path of directory containing lock files generated by instances of this class.

        Returns
        -------
        Path
            The path of the base directory for lock files
        """
        return Path("/tmp/meta-sched")

    def __init__(self: "LockFile", name: str) -> None:
        """
        Create a new instance to guard a critical section.

        Parameters
        ----------
        name : str
            The name of the lock corresponding to the lock file name
        """
        self.__path = LockFile.get_base_path() / name
        self.__path.parent.mkdir(parents=True, exist_ok=True)
        self.__path.touch()
        self.__file: Optional[TextIOWrapper[Any]] = None

    def __enter__(self: "LockFile") -> "LockFile":
        if self.__file:
            raise RuntimeError("Re-entry not allowed")
        self.__file = open(self.__path)
        fcntl.flock(self.__file.fileno(), fcntl.LOCK_EX)
        return self

    def __exit__(
        self: "LockFile", exc_type: Any, exc_value: Any, traceback: Any
    ) -> None:
        if self.__file:
            fcntl.flock(self.__file.fileno(), fcntl.LOCK_UN)
            self.__file.close()
            self.__file = None


class ExponentialBackoff:
    """(Clamped) exponential backoff function."""

    def __init__(
        self: "ExponentialBackoff",
        offset: float = 0,
        factor: float = 1,
        base: float = 2,
        maximum: Optional[float] = 60,
    ) -> None:
        """
        Create a new instance of the exponential backoff function:
        backoff = min(maximum, offset + factor * base**count)

        Parameters
        ----------
        offset : float
            The starting value of the function added as a constant offset (0 by default)
        factor : float
            The factor to be applied to the exponential function (1 by default)
        base : float
            The base of the exponential function (2 by default)
        maximum : Optional[float]
            The maximum value of the backoff function (60 by default) or None if it is unclamped
        """
        self.count = 0
        self.offset = offset
        self.factor = factor
        self.base = base
        self.maximum = maximum

    def __call__(self: "ExponentialBackoff") -> float:
        """Get the current backoff function value.

        Returns
        -------
        float
            The current backoff value
        """
        delay = self.offset + self.factor * self.base**self.count
        if self.maximum is not None:
            delay = min(delay, self.maximum)
        return delay

    def __iadd__(self: "ExponentialBackoff", other: int) -> "ExponentialBackoff":
        """Increment the internal counter (e.g., backoff += 1).

        Parameters
        ----------
        other : int
            The steps by which to increment the backoff function
        """
        if other < 0:
            raise ValueError("Increment must be positive.")
        if not isinstance(other, int):
            raise TypeError("Increment must be an integer.")
        self.count += other
        return self

    def reset(self: "ExponentialBackoff") -> None:
        """Reset the backoff function."""
        self.count = 0


class StatusException(Exception):
    """
    Exception for an exit code of a process.
    """

    def __init__(self, status: int, details: Optional[str] = None) -> None:
        """
        Create a new instance of the exception.

        Parameters
        ----------
        status : int
            The exit code of the corresponding process
        details : Optional[str]
            Additional information about the error
        """
        self.status = status
        self.details = details


def expect_ok(status: int, details: Optional[str] = None) -> None:
    """
    Assert that status is exit code for success.

    Parameters
    ----------
    status : int
        The exit code of a previously executed process
    details : Optional[str]
        Additional information about the (possible) error

    Raises
    ------
    StatusException
        The corresponding process did not exit with status code for success.
    """
    if status != os.EX_OK:
        raise StatusException(status, details)


def sleep(seconds: float) -> float:
    """
    Sleep for the requested number of seconds and ignore EINTR (harmless interrupts).

    Parameters
    ----------
    seconds : float
        Seconds to sleep

    Returns
    -------
    float
        Actual total time slept
    """
    end_time = time.time() + seconds
    slept_total = 0.0

    while True:
        now = time.time()
        remaining = end_time - now
        if remaining <= 0:
            break
        start = time.time()
        try:
            time.sleep(remaining)
            slept_total += time.time() - start
            break  # Finished sleeping without being interrupted
        except InterruptedError as e:
            if getattr(e, "errno", None) == errno.EINTR:
                # Ignore harmless interrupt and continue sleeping
                slept_total += time.time() - start
                continue
            else:
                # Propagate unexpected interrupt
                raise
    return slept_total
