#! /bin/bash

set -e

if [[ "$SHELL" != */bash ]]; then
    echo "Error: Only bash shell is supported!"
    exit 1
fi

COMPONENT=$1

if [[ "$COMPONENT" == "all" ]]; then
    for COMPONENT in client server; do
        $0 $COMPONENT
    done
    echo "=== Done ==="
    exit 0
elif [[ "$COMPONENT" != "client" && "$COMPONENT" != "server" ]]; then
    echo "Usage: $0 <all|client|server>"
    exit 1
fi

PYTHON_VERSION=3.9.21 # Must be exact Python version (MAJOR.MINOR.PATCH)
PROFILE="$HOME/.bashrc"

echo "=== Set up environment ==="
if [[ -z "$(which pyenv)" ]]; then
    echo "--- Install pyenv ---"
    wget -qO- https://pyenv.run | bash
    {
        echo -e '\n# pyenv configuration'
        echo 'export PYENV_ROOT="$HOME/.pyenv"'
        echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"'
        echo 'eval "$(pyenv init - bash)"'
    } >> "$PROFILE"
    # shellcheck source=/dev/null
    source "$PROFILE"
else
    echo "--- Found pyenv ---"
fi

if ! pyenv versions --bare | grep -q "^${PYTHON_VERSION//./\\.}$"; then
    echo "--- Install Python $PYTHON_VERSION ---"
    pyenv install "$PYTHON_VERSION"
else
    echo "--- Found Python $PYTHON_VERSION ---"
fi

PYTHON_BIN="${PYENV_ROOT}/versions/${PYTHON_VERSION}/bin/python3"

if [[ -z "$(which pipx)" ]]; then
    echo "--- Install pipx ---"
    "$PYTHON_BIN" -m pip install --upgrade pip
    "$PYTHON_BIN" -m pip install --user pipx
    "$PYTHON_BIN" -m pipx ensurepath
    # shellcheck source=/dev/null
    source "$PROFILE"
else
    echo "--- Found pipx ---"
fi

echo "=== Install $COMPONENT package ==="

SCRIPT_PATH="$(readlink -f "$0")"
cd "$(dirname "$(dirname "$SCRIPT_PATH")")"

WHEEL=$(find "packages/ms_$COMPONENT/dist/" -type f -name "*.whl" 2>/dev/null || :)

if [[ ! -f $WHEEL ]]; then
    echo "Error: Please package $COMPONENT first!"
    exit 1
fi

echo "--- Uninstall old $COMPONENT package (if present) ---"
pipx uninstall "meta-sched-$COMPONENT" || :

echo "--- Install $COMPONENT package ---"
pipx install $WHEEL --python "$PYTHON_BIN"

echo "--- Done ---"
