#! /bin/bash

set -e

COMPONENT=$1

if [[ "$COMPONENT" == "all" ]]; then
    for COMPONENT in client server; do
        echo "=== Building ms_$COMPONENT package ==="
        $0 $COMPONENT
    done
    echo "=== All done ==="
    exit 0
elif [[ "$COMPONENT" != "client" && "$COMPONENT" != "server" ]]; then
    echo "Usage: $0 <all|client|server>"
    exit 1
fi

PACKAGE="ms_$COMPONENT"

SCRIPT_PATH="$(readlink -f "$0")"
cd "$(dirname "$(dirname "$SCRIPT_PATH")")"
BASE_DIR=$(pwd)

cd "$BASE_DIR/packages/$PACKAGE"

echo "--- Update project ---"
uv sync --upgrade
uv lock --upgrade

cd "$BASE_DIR/src/$PACKAGE"
echo "--- Apply formatting ---"
cd "$BASE_DIR/packages/$PACKAGE"
uv add ruff --dev # Make sure formatter is installed as development dependencies
# shellcheck source=/dev/null
source .venv/bin/activate
# Workaround for virtual environment not activating correctly in some cases
PYTHON=$(pwd)/.venv/bin/python
$PYTHON --version
$PYTHON -m ruff check --fix
$PYTHON -m ruff format

echo "--- Perform static type checking for modules ---"
uv add mypy pyright --dev # Make sure type checkers are installed as development dependencies
cd "$BASE_DIR/src"
echo -n "mypy " && $PYTHON -m mypy --package "$PACKAGE" --package ms_common \
    --strict \
    --follow-untyped-imports \
    --platform linux \
    --python-version 3.12
echo -n "pyright " && PYRIGHT_PYTHON_FORCE_VERSION=latest $PYTHON -m pyright --project "$PACKAGE"

check-coverage-and-annotations() {
    echo "... Check docstring coverage ..."
    uvx docstr-coverage . --skip-magic

    echo "... Check WIP annotations ..."
    TC=$(grep --binary-files=without-match --exclude="*.pyc" -rni todo ./*  | wc -l)
    FC=$(grep --binary-files=without-match --exclude="*.pyc" -rni fixme ./*  | wc -l)
    echo Found "$TC" TODOs and "$FC" FIXMEs in the project.
}

echo "--- Analyze $PACKAGE package ---"
cd "$BASE_DIR/src/$PACKAGE"
check-coverage-and-annotations || :
echo "--- Analyze ms_common package ---"
cd "$BASE_DIR/src/ms_common"
check-coverage-and-annotations || :
echo "--- Done analyzing $PACKAGE package ---"
cd "$BASE_DIR/tests"
check-coverage-and-annotations || :
echo "--- Done analyzing tests ---"

echo "--- Build distributable module ---"
cd "$BASE_DIR/packages/$PACKAGE"
uv build --wheel --quiet
echo "Contents of $BASE_DIR/packages/$PACKAGE/dist/*.whl:"
python3 -m zipfile -l "$(ls "$BASE_DIR"/packages/"$PACKAGE"/dist/*.whl)" | awk '{ print $1 }'
echo "--- Done ---"
